name: DroppedXPItem
version: 0.1
description: DroppedXPItem
author: judgetread
authors: [judgetread] 
website: http://github.com/DroppedXPItem
main: main.java.com.github.judgetread.DroppedXPItem.DroppedXPItem
permissions:
    DroppedXPItem.bypass:
        default: op
        description: Player will not drop xp as DroppedXPItem.
    DroppedXPItem.awardxp:
        default: true
        description: Allows player to pickup/use DroppedXPItem.